plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
}

group = 'org.calipsoide'
version = '0.1.0-SNAPSHOT'

java {
    sourceCompatibility = '25'
    targetCompatibility = '25'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    implementation('org.springframework.boot:spring-boot-starter-webflux')
    implementation('com.google.guava:guava:23.0')
    implementation('org.eclipse.jgit:org.eclipse.jgit:4.8.0.201706111038-r')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testImplementation('org.springframework.boot:spring-boot-webtestclient')
    testImplementation('io.projectreactor:reactor-test')
}

tasks.named('test') {
    useJUnitPlatform()
}
