plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
}

group = 'org.calipsoide'
version = '0.1.0-SNAPSHOT'

java {
    sourceCompatibility = '25'
    targetCompatibility = '25'
}

repositories {
    mavenCentral()
}

dependencies {
    def springBootDependencies = platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    implementation springBootDependencies
    implementation('org.springframework.boot:spring-boot-starter-webflux')
    implementation('com.github.ben-manes.caffeine:caffeine')
    implementation('org.springframework:spring-context-support')
    implementation('org.eclipse.jgit:org.eclipse.jgit:7.7.1.202607240634-r')
    compileOnly springBootDependencies
    compileOnly('org.projectlombok:lombok')
    annotationProcessor springBootDependencies
    annotationProcessor('org.projectlombok:lombok')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testImplementation('org.springframework.boot:spring-boot-webtestclient')
    testImplementation('io.projectreactor:reactor-test')
}

tasks.named('test') {
    useJUnitPlatform()
}
