features:
  git:
    local:
      path: /var/tmp/feature-valves
      data: /var/tmp/feature-valves/features
    remote:
    clone:
      depth: 1
  cache:
    ttl: PT10M
  refresh:
    interval: PT1M

logging:
  level:
    org:
      calipsoide: DEBUG
