features:
  git:
    local:
      path: /var/tmp/feature-valves
      data: /var/tmp/feature-valves/features
    remote:
      url: https://github.com/ehpalumbo/feature-valves.git
      branch: master
  cache:
    ttl: 10
  refresh:
    interval: 20

logging:
  level:
    org:
      calipsoide: DEBUG
