features:
  git:
    local:
      path: /var/tmp/feature-valves
      data: /var/tmp/feature-valves/features
    remote:
    clone:
      depth: 1
  cache:
    ttl: PT10M
  refresh:
    interval: PT1M
    backoff:
      min: PT1S
      max: PT1M
      max-attempts: 5

logging:
  level:
    org:
      calipsoide: DEBUG
