# CI build workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Gradle build
        run: ./gradlew build

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/test/*.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-test-coverage
          path: build/reports/jacoco/test

      - name: Build image
        run: ./gradlew bootBuildImage --imageName "ehpalumbo/feature-valves:${GITHUB_SHA::7}"

      - name: Save image
        if: github.ref == 'refs/heads/master'
        run: docker save "ehpalumbo/feature-valves:${GITHUB_SHA::7}" -o feature-valves.tar

      - name: Upload image artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: feature-valves-image
          path: feature-valves.tar
